### ISSUE TITLE
readme.md - Explanation/docs of current matchers is required

### ISSUE THREAD

**Issue by dgroup** [llorllale/cactoos-matchers#58]
We need to add more information/docs about project functionality to the main page.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/llorllale/cactoos-matchers/issues/58#issuecomment-446404959))

@llorllale @llorllale[/z](https://www.0crat.com/u/llorllale) not enough funds available in the project, can't set budget of job [#58](https://github.com/llorllale/cactoos-matchers/issues/58), see [§21](http://www.zerocracy.com/policy.html#21); @llorllale[/z](https://www.0crat.com/u/llorllale) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @dgroup[/z](https://www.0crat.com/u/dgroup)

**Comment by llorllale** [comment]
@0crat wait because I submitted PR #59 for this

**Comment by 0crat** [comment]
> @0crat wait because I submitted PR #59 for this ([here](https://github.com/llorllale/cactoos-matchers/issues/58#issuecomment-446419657))

@llorllale The impediment for [#58](https://github.com/llorllale/cactoos-matchers/issues/58) was registered successfully by @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
> @0crat wait because I submitted PR #59 for this ([here](https://github.com/llorllale/cactoos-matchers/issues/58#issuecomment-446419657))

@llorllale Job [#58](https://github.com/llorllale/cactoos-matchers/issues/58) is not in the agenda of @llorllale[/z](https://www.0crat.com/u/llorllale), can't set impediment

**Comment by dgroup** [comment]
![image](https://user-images.githubusercontent.com/1651114/49843116-09960e80-fde4-11e8-9d6b-322300a33670.png)
@llorllale, for which purpose its requried? 
It allows 0crat to do not track the time on the issue when you are waiting for the review?

**Comment by llorllale** [comment]
@dgroup yes - it means 0crat won't kick me off the issue.

I don't know why it posted that third message about this job not being in my agenda though..

**Comment by llorllale** [comment]
@0crat status

**Comment by 0crat** [comment]
Job [#58](https://github.com/llorllale/cactoos-matchers/issues/58) is already assigned to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/llorllale/cactoos-matchers/issues/58#issuecomment-451156157))

@llorllale This is what I know about this job in [C63314D6Z](https://www.0crat.com/p/C63314D6Z), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#58](https://github.com/llorllale/cactoos-matchers/issues/58) is [in scope](http://www.zerocracy.com/policy.html#14) for 23days
  * The role is `DEV`
  * The job is assigned to @llorllale[/z](https://www.0crat.com/u/llorllale) for [23days](http://www.zerocracy.com/policy.html#8)
  * @llorllale[/z](https://www.0crat.com/u/llorllale) is on vacation!
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job has an [impediment](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @dgroup[/z](https://www.0crat.com/u/dgroup): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Allorllale%2Fcactoos-matchers%2358%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by llorllale** [comment]
@0crat boost 4x

**Comment by 0crat** [comment]
> @0crat boost 4x ([here](https://github.com/llorllale/cactoos-matchers/issues/58#issuecomment-451163156))

@llorllale @llorllale[/z](https://www.0crat.com/u/llorllale) not enough funds available in the project, can't set budget of job [#58](https://github.com/llorllale/cactoos-matchers/issues/58), see [§21](http://www.zerocracy.com/policy.html#21); @llorllale[/z](https://www.0crat.com/u/llorllale) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0pdd** [comment]
@dgroup 2 puzzles [#68](https://github.com/llorllale/cactoos-matchers/issues/68), [#69](https://github.com/llorllale/cactoos-matchers/issues/69) are still not solved.

**Comment by 0crat** [comment]
Boosting tasks is against our principles, see [§15](http://www.zerocracy.com/policy.html#15): -10 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by llorllale** [comment]
@dgroup fixed in PR #59. Can we close this?

**Comment by 0crat** [comment]
Job [#58](https://github.com/llorllale/cactoos-matchers/issues/58) is not in the agenda of @llorllale[/z](https://www.0crat.com/u/llorllale), can't retrieve data and time of add

**Comment by 0crat** [comment]
The job [#58](https://github.com/llorllale/cactoos-matchers/issues/58) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0pdd** [comment]
@dgroup the puzzle [#68](https://github.com/llorllale/cactoos-matchers/issues/68) is still not solved; solved: [#69](https://github.com/llorllale/cactoos-matchers/issues/69).

**Comment by 0pdd** [comment]
@dgroup all 2 puzzles are solved here: [#68](https://github.com/llorllale/cactoos-matchers/issues/68), [#69](https://github.com/llorllale/cactoos-matchers/issues/69).
