### ISSUE TITLE
Envelope for TypeSafeMatcher - reduce the code duplication within the matchers

### ISSUE THREAD

**Issue by dgroup** [llorllale/cactoos-matchers#75]
`TypeSafeMatcher` was chosen as an example of how to easily implement hamcrest matcher, however, we have code duplication for each implementation of `TypeSafeMatcher`:
 - overriding of 3 methods `match`, `describeTo`, `describeMismatch`
 - for each of these methods, we need the fields in order to constructs the methods
 - most of these methods are operating with cactoos primitives, thus, we are using a lot of `Unchecked` implementations
 - when we were working on Text-based matchers we understood that something went wrong and implement the `TextMatcherEnvelope`. That was a good decision, but we need to extend it to the whole project. `TextMatcherEnvelope` should extend `Envelope`
 - envelope give a standard approach for matcher implementation, for example, the `InputHasContent` has no overridden `describeMismatch` method and this won't happen in case if the envelope was used. It similar to `Assertion` vs`MatcherAssert.assertThat`, when developers skipping the `reason` explanation of test (they can't do that using `Assertion`).

The envelope may look like 
```java
package org.llorllale.cactoos.matchers;

import org.cactoos.BiProc;
import org.cactoos.Func;
import org.cactoos.Proc;
import org.cactoos.func.UncheckedBiProc;
import org.cactoos.func.UncheckedFunc;
import org.cactoos.func.UncheckedProc;
import org.hamcrest.Description;
import org.hamcrest.Matcher;
import org.hamcrest.TypeSafeMatcher;

public class Envelope<T> extends TypeSafeMatcher<T> {

    private final Matcher<T> origin;

    public Envelope(
        final Func<T, Boolean> matches,
        final Proc<Description> describe,
        final BiProc<Description, T> mismatch
    ) {
        this(new TypeSafeMatcher<T>() {
                 @Override
                 public void describeTo(final Description description) {
                     new UncheckedProc<>(describe).exec(description);
                 }

                 @Override
                 protected boolean matchesSafely(final T o) {
                     return new UncheckedFunc<>(matches).apply(o);
                 }

                 @Override
                 protected final void describeMismatchSafely(
                     final T item, final Description desc) {
                    new UncheckedBiProc<>(mismatch).exec(desc, item);
                 }
             }
        );
    }

    public Envelope(final Matcher<T> origin) {
        this.origin = origin;
    }

    @Override
    protected final boolean matchesSafely(final T t) {
        return this.origin.matches(t);
    }

    @Override
    public final void describeTo(final Description desc) {
        this.origin.describeTo(desc);
    }

    @Override
    protected final void describeMismatchSafely(
        final T item, final Description desc) {
        this.origin.describeMismatch(item, desc);
    }
}

```
For example, the `InputHasContent` with envelope will became
```java
public final class InputHasContent extends Envelope<Input> {

    /**
     * Ctor.
     * @param text The text to match against
     */
    public InputHasContent(final String text) {
        this(new TextOf(text));
    }

    /**
     * Ctor.
     * @param text The text to match against
     */
    public InputHasContent(final Text text) {
        this(new MatcherOf<>((String input) -> text.asString().equals(input)));
    }

    /**
     * Ctor.
     * @param mtr Matcher of the text
     */
    public InputHasContent(final Matcher<String> mtr) {
        super(
            input -> mtr.matches(new TextOf(input).asString()),
            desc -> {
                desc.appendText("Input with ").appendDescriptionOf(mtr);
            },
            (desc, input) -> desc.appendText("Input with ").appendValue(
                new TextOf(input).asString()
            )
        );
    }
}
```
which is much shorter than
```java
public final class InputHasContent extends TypeSafeMatcher<Input> {

    /**
     * Matcher of the value.
     */
    private final Matcher<String> matcher;

    /**
     * Ctor.
     * @param text The text to match against
     */
    public InputHasContent(final String text) {
        this(new TextOf(text));
    }

    /**
     * Ctor.
     * @param text The text to match against
     */
    public InputHasContent(final Text text) {
        this(new MatcherOf<>((String input) -> text.asString().equals(input)));
    }

    /**
     * Ctor.
     * @param mtr Matcher of the text
     */
    public InputHasContent(final Matcher<String> mtr) {
        super();
        this.matcher = mtr;
    }

    @Override
    public boolean matchesSafely(final Input item) {
        return this.matcher.matches(
            new UncheckedText(
                new TextOf(item)
            ).asString()
        );
    }

    @Override
    public void describeTo(final Description description) {
        description.appendText("Input with ");
        description.appendDescriptionOf(this.matcher);
    }
}
```

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/llorllale/cactoos-matchers/issues/75#issuecomment-453115840))

@llorllale Job [#75](https://github.com/llorllale/cactoos-matchers/issues/75) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @dgroup[/z](https://www.0crat.com/u/dgroup)

**Comment by 0pdd** [comment]
@dgroup 2 puzzles [#93](https://github.com/llorllale/cactoos-matchers/issues/93), [#94](https://github.com/llorllale/cactoos-matchers/issues/94) are still not solved.

**Comment by borysfan** [comment]
@dgroup Could you please close this issue? It has been resolved in PR #87

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@de00ab27-a2e4-4101-8382-b09a2841d519, thread: AsyncProc-5
com.jcabi.github.RtValuePagination$Items[181] java.lang.IllegalStateException: java.io.IOException: failed after 4 attempts
com.jcabi.http.wire.RetryWire[95] java.io.IOException: failed after 4 attempts
```

[0.40.15](https://github.com/zerocracy/farm): CID: [94497a8f-728e-4ac7-9013-e721ebce6297](https://www.0crat.com/footprint/C63314D6Z/94497a8f-728e-4ac7-9013-e721ebce6297), Type: "Close job"

**Comment by 0crat** [comment]
The job [#75](https://github.com/llorllale/cactoos-matchers/issues/75) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @borysfan[/z](https://www.0crat.com/u/borysfan)

**Comment by 0pdd** [comment]
@dgroup 3 puzzles [#120](https://github.com/llorllale/cactoos-matchers/issues/120), [#121](https://github.com/llorllale/cactoos-matchers/issues/121), [#93](https://github.com/llorllale/cactoos-matchers/issues/93) are still not solved; solved: [#94](https://github.com/llorllale/cactoos-matchers/issues/94).

**Comment by 0pdd** [comment]
@dgroup 3 puzzles [#121](https://github.com/llorllale/cactoos-matchers/issues/121), [#129](https://github.com/llorllale/cactoos-matchers/issues/129), [#93](https://github.com/llorllale/cactoos-matchers/issues/93) are still not solved; solved: [#120](https://github.com/llorllale/cactoos-matchers/issues/120), [#94](https://github.com/llorllale/cactoos-matchers/issues/94).

**Comment by 0pdd** [comment]
@dgroup 2 puzzles [#129](https://github.com/llorllale/cactoos-matchers/issues/129), [#93](https://github.com/llorllale/cactoos-matchers/issues/93) are still not solved; solved: [#120](https://github.com/llorllale/cactoos-matchers/issues/120), [#121](https://github.com/llorllale/cactoos-matchers/issues/121), [#94](https://github.com/llorllale/cactoos-matchers/issues/94).

**Comment by 0pdd** [comment]
@dgroup 2 puzzles [#139](https://github.com/llorllale/cactoos-matchers/issues/139), [#93](https://github.com/llorllale/cactoos-matchers/issues/93) are still not solved; solved: [#120](https://github.com/llorllale/cactoos-matchers/issues/120), [#121](https://github.com/llorllale/cactoos-matchers/issues/121), [#129](https://github.com/llorllale/cactoos-matchers/issues/129), [#94](https://github.com/llorllale/cactoos-matchers/issues/94).

**Comment by 0pdd** [comment]
@dgroup the puzzle [#139](https://github.com/llorllale/cactoos-matchers/issues/139) is still not solved; solved: [#120](https://github.com/llorllale/cactoos-matchers/issues/120), [#121](https://github.com/llorllale/cactoos-matchers/issues/121), [#129](https://github.com/llorllale/cactoos-matchers/issues/129), [#93](https://github.com/llorllale/cactoos-matchers/issues/93), [#94](https://github.com/llorllale/cactoos-matchers/issues/94).

**Comment by 0pdd** [comment]
@dgroup all 6 puzzles are solved here: [#120](https://github.com/llorllale/cactoos-matchers/issues/120), [#121](https://github.com/llorllale/cactoos-matchers/issues/121), [#129](https://github.com/llorllale/cactoos-matchers/issues/129), [#139](https://github.com/llorllale/cactoos-matchers/issues/139), [#93](https://github.com/llorllale/cactoos-matchers/issues/93), [#94](https://github.com/llorllale/cactoos-matchers/issues/94).
